import React from 'react'
import Button from '../shared/Button'

export default function Home(){
  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">Home</h1>
      <p className="mb-4">This is a starter generated by crap-ui.</p>
      <Button text="Click me" />
    </div>
  )
}
